# Official configuration file for Upptime
# https://upptime.js.org/docs/configuration

owner: nsahal # Your GitHub username
repo: status-estimation-pk # Repository name

sites:
  - name: Estimation.pk Website
    url: https://estimation.pk
    icon: https://estimation.pk/favicon.ico
    
  - name: Estimation.pk App
    url: https://app.estimation.pk
    icon: https://estimation.pk/favicon.ico
    expectedStatusCodes:
      - 200
      - 301
    
  - name: API Health Check
    url: https://api.estimation.pk/health
    method: GET
    expectedStatusCodes:
      - 200
      - 503  # Allow degraded status
    
  # Removed: API Calculate Quote endpoint requires authentication
  # Cannot be monitored without valid user token
  # Use API Health Check instead for general API availability
    
  - name: Database Health
    url: https://api.estimation.pk/health/database
    method: GET
    expectedStatusCodes:
      - 200
      - 503
    
  # Removed: /health/auth endpoint doesn't exist in the API
  # Authentication is checked implicitly through other endpoints

status-website:
  # Add your custom domain here
  cname: status.estimation.pk
  
  # Custom logo and favicon (Upptime copies from assets/* to root of gh-pages)
  logoUrl: https://status.estimation.pk/logo.png
  favicon: https://status.estimation.pk/favicon.ico
  
  name: Estimation.pk Status
  
  introTitle: "**Estimation.pk** System Status"
  introMessage: Real-time status and uptime monitoring for Estimation.pk services.
  
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://estimation.pk
  
  # Custom theme settings
  theme: dark
  
  # Custom CSS - Files from assets/* are copied to root of gh-pages
  customCSS: https://status.estimation.pk/custom.css
  
  # Remove Upptime branding
  skipPoweredByUpptime: true
  skipDescriptionWithSummary: true

# Commit messages
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"

# Schedule - Check every 5 minutes
workflowSchedule:
  graphs: "0 0 * * *"  # Update graphs daily
  responseTime: "0 23 * * *"  # Response time daily
  staticSite: "0 1 * * *"  # Update static site daily
  summary: "0 0 * * *"  # Summary daily
  updateTemplate: "0 0 * * *"  # Template updates daily
  updates: "0 3 * * *"  # Check for updates daily
  uptime: "*/5 * * * *"  # Check uptime every 5 minutes

# User agent for requests
user-agent: upptime-bot

# Notification settings (optional - uncomment to enable)
# notifications:
#   - type: slack
#     webhook-url: $SLACK_WEBHOOK_URL
#   - type: discord
#     webhook-url: $DISCORD_WEBHOOK_URL

# Assignment settings
assignees:
  - nsahal

# Default maximum response time (in ms)
maxResponseTime: 5000

# Add delay between requests (in ms) to avoid rate limiting
delay: 1000
